# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]

[default.extend-words]

[files]
extend-exclude = ["package-lock.json", "src/store/project.ts", "*.svg", "pnpm-lock.yaml"]
