# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default]
extend-ignore-re = [
    # // typos:ignore-next-line を使って警告を無視できるようにする
    # https://github.com/crate-ci/typos/issues/316#issuecomment-2886204780
    "(?s)//\\s*typos:ignore-next-line[^\\n]*\\n[^\\n]*",
]

[default.extend-identifiers]
splited = "splited" # コードで使う時、もっと自然な感じを与える

[default.extend-words]
ba = "ba" # 7zコマンドの-baオプション
commitish = "commitish" # softprops/action-gh-releaseのオプションの１つ
GAM = "GAM" # VuexのGetter・Action・Mutationの略

[files]
extend-exclude = [
    "pnpm-lock.yaml",
    "*.svg",
    "public/res/macos-big-sur-software-update-rosetta-alert.jpg", # macos-big-surは正しい固有名詞
]
