# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]

[default.extend-words]
ba = "ba" # 7zコマンドの-baオプション
commitish = "commitish" # softprops/action-gh-releaseのオプションの１つ

[files]
extend-exclude = ["package-lock.json", "src/domain/project/index.ts", "*.svg"]
